spring:
  application:
    name: sync
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
    dynamic:
      p6spy: true
      lazy: true
      # 配置全局druid参数，请按需配置
      druid:
        initial-size: 5
        max-active: 8
        min-idle: 3
        max-wait: 1000
        validation-query: 'select 1'
      datasource:
        master_1:
          username: root
          password: password
          url: jdbc:mysql://localhost:3306/wfw?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false
          driver-name: com.mysql.jdbc.Driver
          schema: schema/sys_user.sql
        master_2:
          username: root
          password: password
          driver-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://localhost:3306/wfw?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false